### ISSUE TITLE
Is stack build broken?

### ISSUE THREAD

**Issue by OlivierSohn** [BlackBrane/ansigraph#2]
Hello,

I'm working on a renderer that avoids screen tearing, so I wanted to see how ansigraph renderer performs to see if there would be any use of my renderer.

I cloned the repo, and tried to build with stack, this is the error I see:

```shell
stack test
The same package name is used in multiple local packages

ansigraph used in:
- PLIndex "ansigraph-0.3.0.4"
- PLOther (PLFilePath ".")
```

Am I doing something wrong?

EDIT : I could build using cabal though so it's a minor issue

**Comment by fieldstrength** [comment]
Thanks for the report! 

This was an error on my part. In the stack configuration the package itself was erroneously listed under `extra-deps`. It's fixed now.

Do let me know if you encounter anything else, or have suggestions.

**Comment by OlivierSohn** [comment]
Cool, I wanted to see if I saw screen tearing, I tried the examples but didn't see any so I don't think there is a valid use case for my package here... Also in this case delta rendering is maybe not appropriate because there are a lot of changes everywhere, so it wouldn't help too much... In any case if you're interested in the subject I explain about it in the doc of this source: https://github.com/OlivierSohn/hamazed/blob/master/imj-base/src/Imj/Render/Delta.hs
